### ISSUE TITLE
[Sorry] Force controller prompts with RF5fix

### ISSUE THREAD

**Issue by AlbertoEberhardt** [davidthemaster30/RF5-AutoPickup#1]

**Comment by davidthemaster30** [comment]
RF5Fix should be able to force controller prompts through the config. If you can't find the config, it should be autogenerated after first launch, in this location : steamapps/common/Rune Factory 5/BepInEx/config/RF5Fix.cfg.

You can then change the values:
```
ControllerOverride = true

# Acceptable values: Xbox, PS4, PS5, Switch
ControllerOverrideType = Xbox
```
If you don't like modify config files, you can also do it via BepInEx Configuration Manager ingame. With it installed, press F1 to open the Configuration Manager Menu. For this config, the game will need to be restarted.
